config/routes.rb
Rails.application.routes.draw do

  namespace :public do
    get 'relationships/following'
    get 'relationships/followers'
  end

  #ユーザー側
  #URL /users/sign_in ...
  devise_for :users, skip: [:passwords], controllers: {
    registrations: 'public/registrations',
    sessions: "public/sessions"
  }

  #管理者側
  #URL /admin/sign_in ...
  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: 'admin/sessions'
  }

  #ゲストログイン
  devise_scope :user do
    post '/users/guest_sign_in' => 'public/sessions#guest_sign_in'
  end

  # 管理者側のルーティング
  namespace :admin do
    resources :users, only: [:index, :edit, :update]
    resources :posts, only: [:index, :edit, :update, :destroy]
    resources :genres, only: [:index, :create, :edit, :update, :destroy]
    resources :comments, only: [:index, :destroy]
  end

  # ユーザー側のルーティング
  scope module: :public do
    root 'homes#top'
    # 投稿ワード検索用
    get 'search' => 'searches#search'
    # ユーザー退会用
    get '/users/confirm' => 'users#confirm'
    patch '/users/withdrawal' => 'users#withdrawal', as: 'withdrawal'
    resources :users, only: [:index, :show, :edit, :update, :destroy] do
      member do
        get :likes
      end
      # フォロー用
      resource :relationships, only: [:create, :destroy]
      get 'followings' => 'relationships#followings', as: 'followings'
      get 'followers' => 'relationships#followers', as: 'followers'
    end
    resources :genres, only: [:show]
    resources :posts do
      # いいね用
      resource :likes, only: [:create, :destroy]
      # コメント用
      resources :comments, only: [:create, :destroy]
    end
    # 通知用
    resources :notifications, only: [:index]
  end
end

app/models/comment.rb
class Comment < ApplicationRecord

  belongs_to :post
  belongs_to :user

  validates :comment, presence: true, length: { minimum: 1, maximum: 500}

end

app/controllers/admin/comments_controller.rb
class Admin::CommentsController < ApplicationController

  def index
    @comments = Comment.all.order(created_at: :desc).page(params[:page]).per(8)
  end

  def destroy
    @comment = Comment.find(params[:id]).destroy
    @comment.destroy
    redirect_to admin_comments_path
  end

end

app/helpers/admin/comments_helper.rb
module Admin::CommentsHelper
end

app/views/admin/comments/index.html.erb
<div class="container py-5">
  <div class="row">

    <div class="col-md-2 text-center mt-5">
      <button type="button" class="btn btn-info text-light rounded-circle p-0 top-btn", style="width:10rem;height:10rem;">
        <h3><strong>Comments</strong></h3>
      </button><br>
      <button type="button" class="btn btn-info rounded-circle p-0 mt-2 mr-5 top-btn", style="width:3rem;height:3rem;"></button><br>
      <button type="button" class="btn btn-info rounded-circle p-0 mt-2 ml-5 top-btn", style="width:1rem;height:1rem;"></button><br>
      <button type="button" class="btn btn-info rounded-circle p-0 mt-2 mr-3 top-btn", style="width:2rem;height:2rem;"></button>
    </div>

    <div class="col-md-9 offset-md-1 py-4">
      <table class="table">
        <tr>
          <th>Comment date</th>
          <th>Comment</th>
          <th>User name</th>
          <th>Delete</th>
        </tr>

        <% @comments.each do |comment| %>
        <tr>
          <td><%= comment.created_at.strftime('%Y/%m/%d') %></td>
          <td style="max-width: 300px;"><%= comment.comment %></td>
          <td><%= comment.user.name %></td>
          <td>
            <%= link_to admin_comment_path(comment.id), method: :delete, "data-confirm" => "本当に削除しますか？" do %>
              <i class="fa-solid fa-trash-can" style="color: ##ff0000;"></i>
            <% end %>
          </td>
        </tr>
        <% end %>
      </table>
      <div>
        <%= paginate @comments %>
      </div>
    </div>

  </div>
</div>