config/routes.rb
Rails.application.routes.draw do

  namespace :public do
    get 'relationships/following'
    get 'relationships/followers'
  end

  #ユーザー側
  #URL /users/sign_in ...
  devise_for :users, skip: [:passwords], controllers: {
    registrations: 'public/registrations',
    sessions: "public/sessions"
  }

  #管理者側
  #URL /admin/sign_in ...
  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: 'admin/sessions'
  }

  #ゲストログイン
  devise_scope :user do
    post '/users/guest_sign_in' => 'public/sessions#guest_sign_in'
  end

  # 管理者側のルーティング
  namespace :admin do
    resources :users, only: [:index, :edit, :update]
    resources :posts, only: [:index, :edit, :update, :destroy]
    resources :genres, only: [:index, :create, :edit, :update, :destroy]
    resources :comments, only: [:index, :destroy]
  end

  # ユーザー側のルーティング
  scope module: :public do
    root 'homes#top'
    # 投稿ワード検索用
    get 'search' => 'searches#search'
    # ユーザー退会用
    get '/users/confirm' => 'users#confirm'
    patch '/users/withdrawal' => 'users#withdrawal', as: 'withdrawal'
    resources :users, only: [:index, :show, :edit, :update, :destroy] do
      member do
        get :likes
      end
      # フォロー用
      resource :relationships, only: [:create, :destroy]
      get 'followings' => 'relationships#followings', as: 'followings'
      get 'followers' => 'relationships#followers', as: 'followers'
    end
    resources :genres, only: [:show]
    resources :posts do
      # いいね用
      resource :likes, only: [:create, :destroy]
      # コメント用
      resources :comments, only: [:create, :destroy]
    end
    # 通知用
    resources :notifications, only: [:index]
  end
end

app/models/genre.rb
class Genre < ApplicationRecord

  has_many :posts, dependent: :destroy
  validates :name, presence: true

end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController

  def index
    @genre = Genre.new
    @genres = Genre.all
  end

  def create
    @genre = Genre.new(genre_params)
    if @genre.save
      flash[:notice] = "ジャンルを投稿しました！"
      redirect_to request.referer
    else
      @genres = Genre.all
      render 'index',alert: "a"
    end
  end

  def update
    genre = Genre.find(params[:id])
    genre.update(genre_params)
    redirect_to admin_genres_path
  end

  def edit
    @genre = Genre.find(params[:id])
  end

  def destroy
    genre = Genre.find(params[:id])
    genre.destroy
    redirect_to admin_genres_path
  end

  private

    def genre_params
      params.require(:genre).permit(:name)
    end

end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/views/admin/genres/edit.html.erb
<div class="container py-5">

  <div class="row">
    <div class="col-md-2 text-center mt-5">
      <button type="button" class="btn btn-secondary rounded-circle p-0 top-btn", style="width:10rem;height:10rem;">
        <h2><strong>Edit genre</strong></h2>
      </button><br>
      <button type="button" class="btn btn-secondary rounded-circle p-0 mt-2 mr-5 top-btn", style="width:3rem;height:3rem;"></button><br>
      <button type="button" class="btn btn-secondary rounded-circle p-0 mt-2 ml-5 top-btn", style="width:1rem;height:1rem;"></button><br>
      <button type="button" class="btn btn-secondary rounded-circle p-0 mt-2 mr-3 top-btn", style="width:2rem;height:2rem;"></button>
    </div>

    <div class="col-md-9 offset-md-1 mt-5">
      <%= form_with model: @genre, url: admin_genre_path, method: :patch do |f| %>
        <table>
          <tr>
            <th class="pt-4"><%= f.label :ジャンル変更 %></th>
          </tr>
          <tr>
            <td class="py-2"><%= f.text_field :name %></td>
          </tr>
          <tr>
            <td class="pt-2 pb-4"><%= f.submit '変更を保存', class: 'btn btn-info' %></td>
          </tr>
        </table>
      <% end %>
      <div class="my-3">
        <%= link_to 'Back', :back %>
      </div>
    </div>

  </div>
</div>

app/views/admin/genres/index.html.erb
<div>
<% if @genre.errors.any? %>
  <%= @genre.errors.count %> 件のエラーが発生しました。
  <ul>
    <% @genre.errors.full_messages.each do |message| %>
     <li><%= message %></li>
    <% end %>
  </ul>
<% end %>
</div>

<div class="container py-5">
  <div class="row">

    <div class="col-md-2 text-center mt-5">
      <button type="button" class="btn btn-info rounded-circle p-0 top-btn", style="width:10rem;height:10rem;">
        <h2><strong>Genres</strong></h2>
      </button><br>
      <button type="button" class="btn btn-info rounded-circle p-0 mt-2 mr-5 top-btn", style="width:3rem;height:3rem;"></button><br>
      <button type="button" class="btn btn-info rounded-circle p-0 mt-2 ml-5 top-btn", style="width:1rem;height:1rem;"></button><br>
      <button type="button" class="btn btn-info rounded-circle p-0 mt-2 mr-3 top-btn", style="width:2rem;height:2rem;"></button>

      <!--ジャンル新規登録フォーム-->
      <%= form_with model: @genre, url: admin_genres_path do |f| %>
      <table class="py-3">
        <tr>
          <td class="pt-3 text-right">Add genre</td>
        </tr>
        <tr>
          <td class="py-2"><%= f.text_field :name %></td>
        </tr>
        <tr>
          <td class="text-right"><%= f.submit '追加', class: "btn btn-success" %></td>
        </tr>
      </table>
      <% end %>
    </div>

    <div class="col-md-9 offset-md-1 py-4">
      <table class="table">
        <tr>
          <th>Genre name</th>
          <th>Genre count</th>
          <th>Edit</th>
          <th>Delete</th>
        </tr>
        <% @genres.each do |genre| %>
        <tr>
          <td>
            <%= link_to genre_path(genre.id), class: "text-decoration-none text-info font-weight-bold" do %>
              <% genre.name %>
            <% end %>
          </td>
          <td><%= genre.posts.count %> 件</td>
          <td>
            <%= link_to edit_admin_genre_path(genre.id) do %>
              <i class="fa-solid fa-gear" style="color: #3953a2;"></i>
            <% end %>
          </td>
          <td>
            <%= link_to admin_genre_path(genre.id), method: :delete, "data-confirm" => "本当に削除しますか？" do %>
              <i class="fa-solid fa-trash-can" style="color: #ff0000;"></i>
            <% end %>
          </td>
        </tr>
        <% end %>
      </table>
    </div>

  </div>
</div>