config/routes.rb
Rails.application.routes.draw do

  namespace :public do
    get 'relationships/following'
    get 'relationships/followers'
  end

  #ユーザー側
  #URL /users/sign_in ...
  devise_for :users, skip: [:passwords], controllers: {
    registrations: 'public/registrations',
    sessions: "public/sessions"
  }

  #管理者側
  #URL /admin/sign_in ...
  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: 'admin/sessions'
  }

  #ゲストログイン
  devise_scope :user do
    post '/users/guest_sign_in' => 'public/sessions#guest_sign_in'
  end

  # 管理者側のルーティング
  namespace :admin do
    resources :users, only: [:index, :edit, :update]
    resources :posts, only: [:index, :edit, :update, :destroy]
    resources :genres, only: [:index, :create, :edit, :update, :destroy]
    resources :comments, only: [:index, :destroy]
  end

  # ユーザー側のルーティング
  scope module: :public do
    root 'homes#top'
    # 投稿ワード検索用
    get 'search' => 'searches#search'
    # ユーザー退会用
    get '/users/confirm' => 'users#confirm'
    patch '/users/withdrawal' => 'users#withdrawal', as: 'withdrawal'
    resources :users, only: [:index, :show, :edit, :update, :destroy] do
      member do
        get :likes
      end
      # フォロー用
      resource :relationships, only: [:create, :destroy]
      get 'followings' => 'relationships#followings', as: 'followings'
      get 'followers' => 'relationships#followers', as: 'followers'
    end
    resources :genres, only: [:show]
    resources :posts do
      # いいね用
      resource :likes, only: [:create, :destroy]
      # コメント用
      resources :comments, only: [:create, :destroy]
    end
    # 通知用
    resources :notifications, only: [:index]
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  validates :name, presence: true, length: { minimum: 1, maximum: 30}, uniqueness: true
  validates :email, presence: true, uniqueness: true

  has_many :posts, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :comments, dependent: :destroy

  # 通知機能。activeは自分からの通知、passiveは相手からの通知。
  has_many :active_notifications, class_name: 'Notification', foreign_key: 'visitor_id', dependent: :destroy
  has_many :passive_notifications, class_name: 'Notification', foreign_key: 'visited_id', dependent: :destroy

  has_one_attached :profile_image

  # 自分 → フォローする側の関係性（与フォロー）
  has_many :relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  # フォロワー → 自分のされる側の関係性（被フォロー）
  has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  # 自分のフォロー一覧
  has_many :followings, through: :relationships, source: :followed
  # 自分のフォロワー一覧
  has_many :followers, through: :reverse_of_relationships, source: :follower

  # フォローする
  def follow(user_id)
    relationships.create(followed_id: user_id)
  end

  # フォローを外す
  def unfollow(user_id)
    relationships.find_by(followed_id: user_id).destroy
  end

  # フォローしているかの確認
  def following?(user)
    followings.include?(user)
  end

  # プロフィール画像編集 （無ければサンプル画像添付）
  def get_profile_image(width, height)
    unless profile_image.attached?
      file_path = Rails.root.join("app/assets/images/no_image.jpg")
      profile_image.attach(io: File.open(file_path), filename: "default-image.jpg", content_type: "image/jpeg")
    end
    profile_image.variant(resize_to_fill: [width, height], gravity: :center).processed
  end

  # ゲストユーザーの検索（存在しなければランダムパスワードで作成）
  def self.guest
    find_or_create_by!(name: "Guest" ,email: "guest@example.com") do |user|
      user.password = SecureRandom.urlsafe_base64
      user.name = "Guest"
    end
  end

  # ユーザー検索
  def self.search(search)
    if search != ""
      User.where(['name LIKE?', "%#{search}%"])
    end
  end

  # 通知作成(フォロー)
  def create_notification_follow!(current_user)
    temp = Notification.where(["visitor_id = ? and visited_id = ? and action = ? ",current_user.id, id, 'follow'])
    # 通知がない場合、作成
    if temp.blank?
      notification = current_user.active_notifications.new(
        visited_id: id,
        action: 'follow'
        )
        notification.save if notification.valid?
    end
  end

  # 登録日計算
  def days_since_created
    # created_atから現在の日付までの経過秒数を計算
    seconds_since_created = (Time.now - created_at).to_i

    # 経過日数を計算
    days = seconds_since_created / (24 * 60 * 60)
    days
  end

end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action :authenticate_admin!

  def index
    @users = User.order(created_at: :desc).page(params[:page]).per(8)
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to admin_users_path, notice: "ユーザープロフィールを編集しました！"
    else
      render :edit
    end
  end

  private
    # カスタムパラメーターを許可
    def user_params
      params.require(:user).permit(:name, :email, :introduction, :is_withdrawal)
    end

end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/views/admin/users/edit.html.erb
<div class="container py-5">
  <div class="row">

    <div class="col-md-2 text-center mt-5">
      <button type="button" class="btn btn-secondary rounded-circle p-0 top-btn", style="width:10rem;height:10rem;">
        <h2><strong>Edit user profile</strong></h2>
      </button><br>
      <button type="button" class="btn btn-secondary rounded-circle p-0 mt-2 mr-5 top-btn", style="width:3rem;height:3rem;"></button><br>
      <button type="button" class="btn btn-secondary rounded-circle p-0 mt-2 ml-5 top-btn", style="width:1rem;height:1rem;"></button><br>
      <button type="button" class="btn btn-secondary rounded-circle p-0 mt-2 mr-3 top-btn", style="width:2rem;height:2rem;"></button>
    </div>

    <div class="col-md-9 offset-md-1 py-4">
      <%= form_with model: @user, url: admin_user_path(@user), method: :patch do |f| %>
      <table>
        <tr>
          <th class="p-3">Registration Date</th>
          <td class="p-3"><%= @user.created_at.strftime('%Y/%m/%d') %></td>
        </tr>
        <tr>
          <th class="p-3">Name</th>
          <td class="p-3"><%= f.text_field :name %></td>
        </tr>
        <tr>
          <th class="p-3">E-mail</th>
          <td class="p-3"><%= f.text_field :email %></td>
        </tr>
        <tr>
          <th class="p-3">Status</th>
          <td>
            <%= f.radio_button :is_withdrawal, :false, checked: true %>
            <%= f.label :is_withdrawal, '有効', { value: :false } %>
            <%= f.radio_button :is_withdrawal, :true %>
            <%= f.label :is_withdrawal, '退会済み', {value: :true} %>
          </td>
        </tr>
        <tr>
          <th class="p-3"><%= f.submit '変更を保存', class: 'btn btn-success' %></th>
          <th class="p-3"></th>
        </tr>
      </table>
      <% end %>
      <div class="m-3">
        <%= link_to 'Back', :back %>
      </div>
    </div>

  </div>
</div>

app/views/admin/users/index.html.erb
<div class="container py-5">
  <div class="row">

    <div class="col-md-2 text-center mt-5">
      <button type="button" class="btn btn-success rounded-circle p-0 top-btn", style="width:10rem;height:10rem;">
        <h2><strong>Users</strong></h2>
      </button><br>
      <button type="button" class="btn btn-success rounded-circle p-0 mt-2 mr-5 top-btn", style="width:3rem;height:3rem;"></button><br>
      <button type="button" class="btn btn-success rounded-circle p-0 mt-2 ml-5 top-btn", style="width:1rem;height:1rem;"></button><br>
      <button type="button" class="btn btn-success rounded-circle p-0 mt-2 mr-3 top-btn", style="width:2rem;height:2rem;"></button>
    </div>

    <div class="col-md-9 offset-md-1 py-4">
      <table class="table">
        <tr>
          <th>Registration Date</th>
          <th>Image</th>
          <th>Name</th>
          <th>Status</th>
          <th>Edit</th>
        </tr>

        <% @users.each do |user| %>
        <tr>
          <td><%= user.created_at.strftime('%Y/%m/%d') %></td>
          <td><%= image_tag user.get_profile_image(60,60), class: "profile_image" %></td>
          <td><%= user.name %></td>
          <td>
            <% if user.is_withdrawal == false %>
              <span class="text-success">有効</span>
            <% else %>
              <span class="text-danger">退会済み</span>
            <% end %>
          </td>
          <td>
            <%= link_to "Edit page", edit_admin_user_path(user.id), class: "text-decoration-none text-info font-weight-bold" %>
          </td>
        </tr>
        <% end %>
      </table>
      <div>
        <%= paginate @users %>
      </div>
    </div>
  </div>
</div>