config/routes.rb
Rails.application.routes.draw do

  namespace :public do
    get 'relationships/following'
    get 'relationships/followers'
  end

  #ユーザー側
  #URL /users/sign_in ...
  devise_for :users, skip: [:passwords], controllers: {
    registrations: 'public/registrations',
    sessions: "public/sessions"
  }

  #管理者側
  #URL /admin/sign_in ...
  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: 'admin/sessions'
  }

  #ゲストログイン
  devise_scope :user do
    post '/users/guest_sign_in' => 'public/sessions#guest_sign_in'
  end

  # 管理者側のルーティング
  namespace :admin do
    resources :users, only: [:index, :edit, :update]
    resources :posts, only: [:index, :edit, :update, :destroy]
    resources :genres, only: [:index, :create, :edit, :update, :destroy]
    resources :comments, only: [:index, :destroy]
  end

  # ユーザー側のルーティング
  scope module: :public do
    root 'homes#top'
    # 投稿ワード検索用
    get 'search' => 'searches#search'
    # ユーザー退会用
    get '/users/confirm' => 'users#confirm'
    patch '/users/withdrawal' => 'users#withdrawal', as: 'withdrawal'
    resources :users, only: [:index, :show, :edit, :update, :destroy] do
      member do
        get :likes
      end
      # フォロー用
      resource :relationships, only: [:create, :destroy]
      get 'followings' => 'relationships#followings', as: 'followings'
      get 'followers' => 'relationships#followers', as: 'followers'
    end
    resources :genres, only: [:show]
    resources :posts do
      # いいね用
      resource :likes, only: [:create, :destroy]
      # コメント用
      resources :comments, only: [:create, :destroy]
    end
    # 通知用
    resources :notifications, only: [:index]
  end
end

app/views/layouts/_errors.html.erb
<% if obj.errors.any? %>
  <div id="error_explanation">
    <h3><%= pluralize(obj.errors.count, "error") %> prohibited this obj from being saved:</h3>
    <ul>
      <% obj.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_footer.html.erb
<footer>
  <div class="container">
    <div class="row justify-content-center">
      <span class="mr-3">Copyright© <strong>Acuario</strong> All right reserved.</span>
       |
      <span><a href="#"><i class="fa-brands fa-x-twitter mx-3" style="color: #ffffff;"></i></a></span>
       |
      <span><a href="#"><i class="fa-brands fa-instagram mx-3" style="color: #ffffff;"></i></a></span>
       |
      <span><a href="#"><i class="fa-brands fa-line mx-3" style="color: #ffffff;"></i></i></a></span>
       |
      <span><a href="#"><i class="fa-brands fa-facebook mx-3" style="color: #ffffff;"></i></i></a></span>
       |
      <span><a href="#"><i class="fa-brands fa-youtube ml-3" style="color: #ffffff;"></i></i></a></span>

    </div>
  </div>
</footer>

app/views/layouts/_header.html.erb
<header>
  <!--ナビゲーションバー-->
  <nav class="navbar navbar-expand-lg">
    <div class="container">

      <!--ヘッダーロゴ-->
      <%= link_to root_path do %>
        <%= image_tag("acuario.png", width: 90, height: 90) %>
      <% end %>

      <!--メニュー-->
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarNavDropdown">

        <div>
          <% if user_signed_in? %>
            ようこそ、 <strong><%= current_user.name %></strong> さん！
          <% end %>
        </div>
        <ul class="navbar-nav ml-auto">

          <!--ユーザー側ログイン-->
          <% if user_signed_in? %>
            <li class="nav-item">
              <%= link_to user_path(current_user.id),class: 'nav-link text-light' do %>
                <i class="fas fa-home"></i> <strong>Home</strong>
              <% end %>
            </li>
            <li class="nav-item">
              <%= link_to users_path,class: 'nav-link text-light' do %>
                <i class="fa-solid fa-people-group"></i> <strong>Users</strong>
              <% end %>
            </li>
            <li class="nav-item">
              <%= link_to posts_path,class: 'nav-link text-light' do %>
                <i class="fa-solid fa-tower-cell"></i> <strong>Posts</strong>
              <% end %>
            </li>
            <li class="nav-item">
              <%= link_to destroy_user_session_path, method: :delete, class: 'nav-link text-light' do %>
                <i class="fas fa-sign-out-alt"></i> <strong>Log out</strong>
              <% end %>
            </li>

            <!--通知-->
            <li class="nav-item">
              <%= link_to notifications_path, class: 'nav-link' do %>
                <% if unchecked_notifications.any? %>
                  <i class="fa-solid fa-bell" style="color: #eeff00;"></i>
                <% else %>
                  <i class="fa-solid fa-bell-slash" style="color: #ffffff;"></i>
                <% end %>
              <% end %>
            </li>

            <li class="nav-item pt-2 pl-2">
             <div>
               <%= render '/public/searches/search' %>
             </div>
            </li>

          <!--管理者側ログイン-->
          <% elsif admin_signed_in? %>
            <li class="nav-item">
              <%= link_to admin_users_path,class: 'nav-link text-light' do %>
                <i class="fa-solid fa-people-group"></i> <strong>Users</strong>
              <% end %>
            </li>
            <li class="nav-item">
              <%= link_to admin_posts_path,class: 'nav-link text-light' do %>
                <i class="fa-solid fa-tower-cell"></i> <strong>Posts</strong>
              <% end %>
            </li>
            <li class="nav-item">
              <%= link_to admin_comments_path,class: 'nav-link text-light' do %>
                <i class="fa-solid fa-comments"></i> <strong>Comments</strong>
              <% end %>
            </li>
            <li class="nav-item">
              <%= link_to admin_genres_path,class: 'nav-link text-light' do %>
                <i class="fa-solid fa-bars-staggered"></i> <strong>Genres</strong>
              <% end %>
            </li>
            <li class="nav-item">
              <%= link_to destroy_admin_session_path, method: :delete, class: 'nav-link text-light' do %>
                <i class="fas fa-sign-out-alt"></i> <strong>Log out</strong>
              <% end %>
            </li>

          <!--ログイン前-->
          <% else %>
            <li class="nav-item">
              <%= link_to new_user_registration_path, class: 'nav-link text-light' do %>
                <i class="fas fa-user-plus"></i> <strong>Sign up</strong>
              <% end %>
            </li>
            <li class="nav-item">
              <%= link_to new_user_session_path, class: 'nav-link text-light' do %>
                <i class="fas fa-sign-in-alt"></i> <strong>Log in</strong>
              <% end %>
            </li>
            <li class="nav-item">
              <%= link_to users_guest_sign_in_path, method: :post, class: 'nav-link text-light' do %>
                <i class="fa-solid fa-person-circle-check"></i> <strong>Guest</strong>
              <% end %>
            </li>
            <li class="nav-item pt-2 pl-2">
             <div>
               <%= render '/public/searches/search' %>
             </div>
            </li>
          <% end %>

        </ul>
      </div>
    </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Acuario</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <!--scrollreveal-->
    <script src="https://unpkg.com/scrollreveal"></script>

    <!--fontawesome-->
    <script src="https://kit.fontawesome.com/838f32accd.js" crossorigin="anonymous"></script>

    <!--google fonts-->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Mooli&display=swap" rel="stylesheet">

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "layouts/header" %>
    <% if flash[:notice] %>
      <div class="notice">
        <p><%= notice %></p>
      </div>
    <% end %>
    <% if flash[:alert] %>
      <div class="alert">
        <p><%= alert %></p>
      </div>
    <% end %>
    <%= yield %>
    <%= render "layouts/footer" %>
  </body>
</html>